import styled from "@emotion/styled";

import TeamHero from "@/modules/Team/TeamHero";
import Head from "next/head";

const AboutContainer = styled.section`
	.about__content {
		overflow: hidden;
		width: 100%;
		padding: 36px;
	}
`;

export default function Caidi() {
	return (
		<>
			<Head>
				<title>MGV- Caidi Mammas Vanderporten</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AboutContainer>
				<TeamHero />
				<div className="about__content"></div>
			</AboutContainer>
		</>
	);
}
