import { useState } from "react";
import styled from "@emotion/styled";

import Team from "@/modules/Team/Index";
import TeamHero from "@/modules/Team/TeamHero";
import AttorneyProfile from "@/modules/Team/AttorneyProfile";
import { motion } from "motion/react";
import Head from "next/head";
import { Attorney } from "@/types/types";

const AboutContainer = styled.section`
	.about__content {
		overflow: hidden;
		width: 100%;
	}

	.about__slider {
		display: flex;
		width: 200%;
	}
`;

export default function About() {
	const attorneys = [
		{
			name: "Evan Mammas",
			title: "Attorney at Law, Founding Partner",
			description:
				"Mammas Goldberg was founded in 1981 by Evan Mammas and Jerry Goldberg with a shared commitment to exceptional family law representation. That legacy continues today through thoughtful advocacy and decades of experience.",
			image: "/images/team/evan-mammas.jpg",
			link: "/about/evan"
		},
		{
			name: "Caidi Mammas Vanderporten",
			title: "Attorney at Law, Partner",
			description:
				"Caidi Mammas Vanderporten continues the firm's tradition of providing dedicated and compassionate family law representation.",
			image: "/images/team/caidi-mammas-vanderporten.jpg",
			link: "/about/caidi",
			reverse: true
		},
		{
			name: "Hailey Vucsko",
			title: "Attorney at Law, Associate",
			description:
				"Hailey brings thoughtful counsel and a commitment to achieving the best possible outcomes for every client.",
			image: "/images/team/hailey-vucsko.jpg",
			link: "/about/hailey"
		}
	];

	const [selectedAttorney, setSelectedAttorney] = useState<Attorney | null>(
		null
	);
	return (
		<>
			<Head>
				<title>MGV- About</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AboutContainer>
				<TeamHero />
				<div className="about__content">
					<motion.div
						className="about__slider"
						animate={{
							x: selectedAttorney ? "-100%" : "0%"
						}}
						transition={{
							duration: 0.6,
							ease: [0.4, 0, 0.2, 1]
						}}
					>
						<Team
							key="team"
							attorneys={attorneys}
							setSelectedAttorney={setSelectedAttorney}
						/>

						<AttorneyProfile
							selectedAttorney={selectedAttorney}
							setSelectedAttorney={setSelectedAttorney}
						/>
					</motion.div>
				</div>
			</AboutContainer>
		</>
	);
}
