import styled from "@emotion/styled";

import Team from "@/modules/Team/Index";
import TeamHero from "@/modules/Team/TeamHero";
import Head from "next/head";

const AboutContainer = styled.section`
	.about__content {
		overflow: hidden;
		width: 100%;
	}
`;

export default function About() {
	const attorneys = [
		{
			name: "Evan Mammas",
			title: "Attorney at Law, Founding Partner",
			description:
				"Mammas Goldberg was founded in 1981 by Evan Mammas and Jerry Goldberg with a shared commitment to exceptional family law representation. That legacy continues today through thoughtful advocacy and decades of experience.",
			image: "/images/team/evan-mammas.jpg",
			link: "/about/evan-mammas"
		},
		{
			name: "Caidi Mammas Vanderporten",
			title: "Attorney at Law, Partner",
			description:
				"Caidi Mammas Vanderporten continues the firm's tradition of providing dedicated and compassionate family law representation.",
			image: "/images/team/caidi-mammas-vanderporten.jpg",
			link: "/about/caidi-mammas-vanderported",
			reverse: true
		},
		{
			name: "Hailey Vucsko",
			title: "Attorney at Law, Associate",
			description:
				"Hailey brings thoughtful counsel and a commitment to achieving the best possible outcomes for every client.",
			image: "/images/team/hailey-vucsko.jpg",
			link: "/about/hailey-vucsko"
		}
	];

	return (
		<>
			<Head>
				<title>MGV- About</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AboutContainer>
				<TeamHero />
				<div className="about__content">
					<Team key="team" attorneys={attorneys} />
					{/* H2: Jerry Goldberg
SUB: In Memoriam: 1951 - 2016
COPY: Jerry was a co-founding partner of MAMMAS GOLDBERG in 1981. Jerry obtained his undergraduate degree from Northern Illinois University and earned his Juris Doctor Degree from IIT - Chicago Kent College of Law. Jerry practiced exclusively in family law, having specialized during the last several years as an advocate and child representative in child custody and visitation cases.
 */}
				</div>
			</AboutContainer>
		</>
	);
}
