import ContactForm from "@/modules/ContactForm/Index";
import Head from "next/head";

export default function Contact() {
	return (
		<>
			<Head>
				<title>MGV- Contact</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<ContactForm />
			</div>
		</>
	);
}
